text:
  use: true #使用开关
  id: '文字'
  x: 0
  y: 2.7 #最好不要低于2.7
  z: 0
  prefix: '§a' #字体前缀，主要用来自定义颜色。
  length: 10 #单行的最大字数，请勿为0
  black: true #背景是否无黑框
  tag:
    x: 0
    y: 0
    z: 0
    for: true #跟随玩家（跟随显示该Tag的玩家转向而转向）,否则跟随视野（如同玩家名称，始终朝向另一个玩家看他的视野）
    see: true #拥有这个Tag玩家是否可以自己的Tag（就是除了自己以外其他所有人都看得到）
image:
  use: false #2.4有转BUG  图片不推荐使用 （BUG已反馈，下个版本2.4.2应该就可以使用这个了） 如果要使用 推荐下面的for属性改成false
  id: '背景'
  x: 0
  y: 3 #已提供自适应  此数值比text的y推荐高1-5 (根据背景来调)
  z: 0.01 #比文字多0.01  就能把图片贴在文字背后
  url: '[local]item.png'
  w: 80
  h: 30
  xshow: 3
  yshow: 0.4 #这个显示高度已经自适应  推荐边框高度  然后中间是内容
  tag:
    x: 0
    y: 0
    z: 0
    for: true #跟随玩家（跟随显示该Tag的玩家转向而转向）,否则跟随视野（如同玩家名称，始终朝向另一个玩家看他的视野） （BUG已反馈，下个版本2.4.2应该就可以使用这个了）
    see: true #拥有这个Tag玩家是否可以自己的Tag（就是除了自己以外其他所有人都看得到）
time: 5 # 聊天显示的持续时间